from selenium.webdriver.common.by import By


class PageLocators:
    SEARCH_FIELD = (By.CSS_SELECTOR, "textarea[type='search']")
    IMAGE_WITH_WEATHER = (By.CSS_SELECTOR, "img[class='wob_tci']")
    FIRST_SEARCH = (By.CSS_SELECTOR, "div[class='TzHB6b cLjAic K7khPe']")
    GO_TO_THE_FIRST_SEARCH = (By.CSS_SELECTOR, "div[class*='TbwUpd NJj']")
    GOOGLE_LOGO = (By.CSS_SELECTOR, "a[title='Go to Google Home']")
    SIGN_IN_BUTTON = (By.CSS_SELECTOR, "span[class*='gb']")
    ELEMS_GO_NEXT = (By.CSS_SELECTOR, "span[jsname='V67aGc']")
    BUTTON_FOR_PERSONAL_USE = (By.CSS_SELECTOR, "span[jsname='K4r5Ff']")
    TEXT_INPUT = (By.CSS_SELECTOR, "input[type='text']")
    NUM_INPUT = (By.CSS_SELECTOR, "input[type='tel']")
    EMAIL_INPUT = (By.CSS_SELECTOR, "input[type='email']")
    DATE_LIST = (By.CSS_SELECTOR, "select[class='UDCCJb']")
    RADIO_BUTTON = (By.CSS_SELECTOR, "div[class='enBDyd ']")
    TEXT_CHOOSE_YOU_GMAIL_ADDRES = (By.CSS_SELECTOR, "span[jsslot]")
    PASSWORD_INPUT = (By.CSS_SELECTOR, "input[type='password']")
    BUTTON_SKIP_NEXT = (By.CSS_SELECTOR, "button[class*='VfPpkd']")
    ELEM_IF_USERNAME_IS_TAKEN = (By.CSS_SELECTOR, "div[class*='o6c']")
    SVG_ERROR_PAGE_OPENING = (By.CSS_SELECTOR, "svg[xmlns='http://www.w3.org/2000/svg']")
    RESULT_STATS = (By.CSS_SELECTOR, "div[id='result-stats']")
    GO_NEXT = (By.CSS_SELECTOR, "button[class*='VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP']")
    GO_TO_IMAGE = (By.CSS_SELECTOR, "a[jsname*='VIftV']")
    GOOGLE_LENS = (By.CSS_SELECTOR, "svg[class*='sFpEPc']")
    INPUT_GOOGLE_LENS = (By.CSS_SELECTOR, "input[data-ved*='0CA4Q3vIIah']")
    SEARCH_GOOGLE_LENS = (By.CSS_SELECTOR, "div[data-ved*='0CA8Q']")
    ERROR_TEXT_GOOGLE_LENS = (By.CSS_SELECTOR, "span[data-ved*='0CAkQvYAJa']")
    GOOGLE_MAPS = (By.CSS_SELECTOR, "a[href='https://maps.google.com/']")
    INPUT_IN_GOOGLE_MAPS = (By.CSS_SELECTOR, "input[jslog='11886']")
    TEXT_IN_GOOGLE_MAPS = (By.CSS_SELECTOR, "div[class='Q2vNVc']")